#!/bin/bash

# Uninstall older versions of docker
sudo apt remove -y docker docker-engine docker.io containerd runc

# Update the apt package index 
sudo apt update -y

# Install packages to allow apt to use a repository over HTTPS
sudo apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo apt-key fingerprint 0EBFCD88


